### PR TITLE
Update support/HAFS from NCAR dtc/hwrf-physics 2020/06/19

### PR DESCRIPTION
**Pull request by climbfuji**
This PR adds the HWRF physics to fv3atm. All development was made in the NCAR fork, branch dtc/hwrf-physics. Commit log from this branch:
```
04/06/2020 MONINEDMF https://github.com/NCAR/fv3atm/pull/18 -> https://github.com/NCAR/fv3atm/pull/37
    git cherry-pick 80ce8591b6af615c9f85a2b3becf8aadc836d734

04/08/2020 RRTMG https://github.com/NCAR/fv3atm/pull/33 -> https://github.com/NCAR/fv3atm/pull/38
    git cherry-pick 1bae50c9fd5a365226088d861b9d80af9b60de7d
    git cherry-pick ed8347eb0f001de2f53989054c024ad24394a483
    git cherry-pick f1cad8833735ce833bc2ed08a318b77c04e3f536
    git cherry-pick d9841c8d353c262c5aa8e0394ab3ed02542ca8f6
    git cherry-pick 3c64b5a3eaa7608edef1d7c91066d4265e442b27

04/13/2020 SAS https://github.com/NOAA-EMC/fv3atm/pull/93 -> https://github.com/NCAR/fv3atm/pull/41
    (entire PR)

04/16/2020 FA MP updates https://github.com/NCAR/fv3atm/pull/28 -> https://github.com/NCAR/fv3atm/pull/43
    (entire PR)

05/04/2020 FA/HWRF RRTMG/HWRF SAS bugfixes https://github.com/NCAR/fv3atm/pull/47
    (entire PR)

05/14/2020 SDFs for HWRF physics test https://github.com/NCAR/fv3atm/pull/44 -> https://github.com/NCAR/fv3atm/pull/50
    (entire PR)

05/20/2020 update from HAFS community https://github.com/NCAR/fv3atm/pull/50
    (entire PR)

06/18/2020 modify HAFS_v0_hwrf_nogwdps SDF https://github.com/NCAR/fv3atm/pull/55
    (entire PR)

06/18/2020 update from HAFS community https://github.com/NCAR/fv3atm/pull/54
    (entire PR)
```

Associated PRs:
https://github.com/hafs-community/ufs-weather-model/pull/5
https://github.com/hafs-community/fv3atm/pull/5
https://github.com/hafs-community/ccpp-physics/pull/2

For regression testing information, see below https://github.com/hafs-community/ufs-weather-model/pull/5.

### CODE REVIEW

**Review by mzhangw — DISMISSED** [review]
looks good to me.

**Review by ChunxiZhang-NOAA — DISMISSED** [review]
1. Note that suite_FV3_HAFS_ferhires.xml is based on 2019 HAFS configuration
2. Note that suite_HAFS_v0_hwrf turns GWD on
3. Note that 'hurr_pbl' is a NEW flag for hurricane-specific options in PBL scheme

**Review by ligiabernardet — DISMISSED** [review]

**Review by WeiguoWang-NOAA — DISMISSED** [review]

**Review by BinLiu-NOAA — DISMISSED** [review]
Ready to merge after the ccpp-physics PR goes into support/HAFS.

**Comment by climbfuji** [comment]
@BinLiu-NOAA please check again, looks good from my end after the submodule pointer update for ccpp-physics.

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good to me. Please proceed with the merge. Thanks!

**Pull request merged**
