### PR TITLE
Merge feature/hafs_nest_sync_gjt back into feature/hafs_nest_cpl

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
Merge feature/hafs_nest_sync_gjt back into feature/hafs_nest_cpl

### CODE REVIEW

**Review by danrosen25 — APPROVED** [review]
Looks good!

**Review by theurich — APPROVED** [review]
Looks good to go.

**Comment by BinLiu-NOAA** [comment]
Thanks, @danrosen25 and @theurich! I am merge this PR and then conduct test from my end. In the meantime, please let me know if you want to keep the feature/hafs_nest_sync_gjt branch, otherwise I will delete it after merging this PR. Thanks!

**Comment by theurich** [comment]
Thanks @BinLiu-NOAA. It's okay with me to delete the feature/hafs_nest_sync_gjt branch now that it is merged.

**Comment by danrosen25** [comment]
Please delete feature/hafs_nest_sync_gjt and I think we should delete feature/hafs_nest_sync too.

We only need hafs_nest_cpl now.

**Pull request merged**
